default_platform :ios

platform :ios do
  
  desc "Build app"
  lane :build do
    gym(
      scheme: "calc",
      clean: true
    )
    puts "OK"
  end

  desc "Run tests"
  lane :test do |options|
    device = options[:device] || "iPhone 16"
    ios_version = options[:ios_version] || "18.3"
    
    scan(
      scheme: "calc",
      clean: true,
      result_bundle: true,
      output_directory: "test_results",
      device: "#{device} (#{ios_version})",
      skip_build: true
    )
    puts "OK"
    puts "Report: test_results/*.xcresult"
  end
  
  desc "Clean results"
  lane :clean do
    sh "rm -rf test_results"
    sh "rm -rf build"
    puts "OK"
  end
  
end
