default_platform :ios

platform :ios do
  
  desc "Build app"
  lane :build do
    gym(
      scheme: "calc",
      clean: true,
      skip_archive: true,
      skip_codesigning: true
    )
    puts "OK"
  end

  desc "Run tests"
  lane :test do
    scan(
      scheme: "calc",
      clean: true,
      result_bundle: true,
      output_directory: "test_results",
      device: "iPhone 16 (18.3)"
    )
    puts "OK"
    puts "Report: test_results/*.xcresult"
  end
  
  desc "Clean results"
  lane :clean do
    sh "rm -rf test_results"
    sh "rm -rf build"
    puts "OK"
  end
  
end
